# Generated by Django 5.2.4 on 2025-07-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payroll.employee')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, help_text='House Rent Allowance', max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
